### ISSUE TITLE
Configuration bad error - Vocabulary file is expected to contain an entry for </s>

### ISSUE THREAD

**Issue by AmitMY** [marian-nmt/marian-dev#282]
This error does not disambiguate cases where the vocab path is invalid.
If I just write a random file name for vocabs, it says the following, which is true, but also not accurate.

> [2018-08-17 09:39:21] [data] Loading vocabulary from text file dasdasdas.en
> [2018-08-17 09:39:21] Vocabulary file dasdasdas.en is expected to contain an entry for </s>

I think it is preferable to add an error "Could not open vocab file" or something.

Furthermore, even if my file does exist, and I created the vocabulary myself from a word vectors file (because I couldn't find a way to create vocabs from word vectors) in the following manner, I still get this error even though `</s>` exists as a key.
```python
from sys import argv
import yaml

if len(argv) < 2:
    raise RuntimeError("Must include word vectors file")

file_name = argv[1]

words = ["</s>", "<unk>"]
with open(file_name, "r") as lines:
    for line in lines:
        vector = line.split()
        words.append(vector.pop(0))

data = {w: i for w, i in zip(words, range(len(words)))}
with open(file_name + ".vocab", "w") as outfile:
    yaml.dump(data, outfile, default_flow_style=False)

print("Created", file_name + ".vocab")
```

This results the following file for example (for character embedding file):
```yaml
'!': 72
'"': 48
'#': 25
$: 2
'%': 73
'&': 49
'''': 26
(: 3
): 74
'*': 50
+: 27
',': 4
'-': 75
.: 51
/: 28
'0': 5
'1': 76
'2': 52
'3': 29
'4': 6
'5': 77
'6': 53
'7': 30
'8': 7
'9': 78
':': 54
;: 31
<: 8
</s>: 0
<unk>: 1
'=': 79
'>': 55
'?': 32
'@': 9
A: 80
B: 56
C: 33
D: 10
E: 81
F: 57
G: 34
H: 11
I: 82
J: 58
K: 35
L: 12
M: 83
N: 59
O: 36
P: 13
Q: 84
R: 60
S: 37
T: 14
U: 85
V: 61
W: 38
X: 15
Y: 86
Z: 62
'[': 39
\: 16
']': 87
^: 63
_: 40
'`': 17
a: 88
b: 64
c: 41
d: 18
e: 89
f: 65
g: 42
h: 19
i: 90
j: 66
k: 43
l: 20
m: 91
n: 67
o: 44
p: 21
q: 92
r: 68
s: 45
t: 22
u: 93
v: 69
w: 46
x: 23
y: 94
z: 70
'{': 47
'|': 24
'}': 95
'~': 71
```

**Comment by emjotde** [comment]
Hi,
It seems I cannot reproduce any of those. The posted vocabulary works fine for me. Can you post your full commands or configurations you used?

**Comment by AmitMY** [comment]
Sure.

This is my full config:
```yaml
# config.yml
type: transformer
train-sets:
  - data/out/train/linear.txt
  - data/out/train/delex.txt
valid:
  - data/out/dev/linear.txt
  - data/out/dev/delex.txt
valid-freq: 5000
disp-freq: 500
valid-metrics:
  - cross-entropy
  - translation
early-stopping: 10
workspace: 4096
mini-batch: 32
model: model/checkpoint/model.npz
tied-embeddings-all: true
vocabs:
  - vocab.en
  - vocab.en
dim-emb: 300
allow-unk: true
```

This is how I train:
```sh
